
version: '3'
services:
    client:
        container_name: maxplorateur-client
        build: ./client
        ports:
            - 80:80
        links:
            - server
    server:
        container_name: maxplorateur-server
        restart: always
        build: ./server
        environment:
            - DB_URL=${DB_URL}
            - FRONT_PORT=${FRONT_PORT}
        ports:
            - 3000:3000