version: '3'

services:
    backend:
        build:
            context: ./server
            dockerfile: Dockerfile
        container_name: backend
        restart: always
        environment:
            - DB_URL=${DB_URL}
            - JWT_SECRET=${JWT_SECRET}
            - JWT_DURATION=${JWT_DURATION}
            - SCHEDULE=${SCHEDULE}
            - EMAIL=${EMAIL}
            - PASSWORD=${PASSWORD}
            - DELAY=${DELAY}
            - WHITELIST=${WHITELIST}
        ports:
            - 3000:3000
        networks:
            - maxplorateur-network
    nginx:
        container_name: nginx
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./client/nginx:/etc/nginx/conf.d
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - dhparam:/etc/ssl/certs
        depends_on:
            - backend
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        networks:
            - maxplorateur-network
    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
        depends_on:
            - backend
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes:
    certbot-etc:
    certbot-var:
    dhparam:
        driver: local
        driver_opts:
          type: none
          device: /home/benoitdemaegdt/TGVmax/dhparam/
          o: bind
networks:
    maxplorateur-network:
        driver: bridge