version: '3'

services:
    backend:
        build:
            context: ./server
            dockerfile: Dockerfile
        container_name: backend
        restart: always
        environment:
            - DB_URL=${DB_URL}
            - JWT_SECRET=${JWT_SECRET}
            - JWT_DURATION=${JWT_DURATION}
            - SCHEDULE=${SCHEDULE}
            - EMAIL=${EMAIL}
            - PASSWORD={PASSWORD}
            - DELAY=${DELAY}
            - WHITELIST=${WHITELIST}
        ports:
            - 3000:3000
        networks:
            - maxplorateur-network
    nginx:
        container_name: nginx
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - 80:80
        volumes:
            - ./client/nginx:/etc/nginx/conf.d
        depends_on:
            - backend
        networks:
            - maxplorateur-network
networks:
    maxplorateur-network:
        driver: bridge